name: Arkitect

on:
  push:
    branches:
      - master
    tags:
      - '*'
  release:
    types:
      - published
      - created
  
jobs:
  create_phar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        #if: steps.composer-cache.outputs.cache-hit != 'true'
        uses: php-actions/composer@v5
        with:
          args: --prefer-dist
          composer_version: 2
          php_version: 7.1

      - name: "Compile phparkitect phar"
        run: ./bin-stub/box.phar build -c ./box.json

      - name: "Upload phar file artifact"
        uses: actions/upload-artifact@v2
        with:
          name: phparkitect.phar
          path: phparkitect.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
